name: CI/CD MERN App to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      EC2_USER: ubuntu
      EC2_HOST: ec2-54-90-80-102.compute-1.amazonaws.com
      IMAGE_TAG: build-${{ github.run_number }}

    steps:

    - name: 📥 Checkout Code
      uses: actions/checkout@v4

    - name: 🐳 Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: 🐳 Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: 🐳 Build Docker Images
      run: docker compose build

    - name: 📦 Push Docker Images to DockerHub
      run: docker compose push

    - name: 🚀 SSH & Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ env.EC2_HOST }}
        username: ${{ env.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd mern-app
          git pull
          docker-compose down
          docker-compose up -d

    - name: ✅ Send Slack Notification (on success)
      if: success()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: "*✅ Build #${{ github.run_number }}* succeeded and deployed to EC2!"

    - name: ❌ Send Slack Notification (on failure)
      if: failure()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_COLOR: danger
        SLACK_MESSAGE: "*❌ Build #${{ github.run_number }}* failed. Check GitHub Actions logs."

